// Development mode utilities for displaying the app without environment variables
import { Decimal } from "@prisma/client/runtime/library"

export const DEV_MODE = process.env.DEV_MODE === "true" || !process.env.SUPABASE_URL

export const mockFacilities = [
  {
    id: "fac-001",
    name: "Acme Industrial Park",
    permitId: "CA0001234",
    naics: "332710",
    lat: new Decimal("34.0522"),
    lon: new Decimal("-118.2437"),
    county: "Los Angeles",
    watershedHuc12: "180701020304",
    ms4: "Los Angeles County",
    receivingWater: "Los Angeles River",
    isInDAC: false,
    enrichedAt: new Date(),
    createdAt: new Date(Date.now() - 365 * 24 * 60 * 60 * 1000),
    lastSeenAt: new Date(),
  },
  {
    id: "fac-002",
    name: "Bay Area Manufacturing",
    permitId: "CA0005678",
    naics: "336411",
    lat: new Decimal("37.8044"),
    lon: new Decimal("-122.2712"),
    county: "Alameda",
    watershedHuc12: "180500020401",
    ms4: "Alameda County",
    receivingWater: "San Francisco Bay",
    isInDAC: true,
    enrichedAt: new Date(),
    createdAt: new Date(Date.now() - 300 * 24 * 60 * 60 * 1000),
    lastSeenAt: new Date(),
  },
  {
    id: "fac-003",
    name: "Central Valley Processing",
    permitId: "CA0009012",
    naics: "311615",
    lat: new Decimal("35.3733"),
    lon: new Decimal("-119.0187"),
    county: "Kern",
    watershedHuc12: "180300030102",
    ms4: null,
    receivingWater: "Kern River",
    isInDAC: true,
    enrichedAt: new Date(),
    createdAt: new Date(Date.now() - 400 * 24 * 60 * 60 * 1000),
    lastSeenAt: new Date(),
  },
]

export const mockViolations = [
  {
    id: "vio-001",
    facilityId: "fac-001",
    pollutant: "Total Nitrogen",
    count: 3,
    exceedanceCount: 3,
    maxRatio: new Decimal("2.5"),
    severity: "HIGH",
    firstDate: new Date(Date.now() - 14 * 24 * 60 * 60 * 1000),
    lastDate: new Date(Date.now() - 7 * 24 * 60 * 60 * 1000),
    reportingYear: "2024",
    impairedWater: true,
    dismissed: false,
    notes: null,
    createdAt: new Date(Date.now() - 14 * 24 * 60 * 60 * 1000),
  },
  {
    id: "vio-002",
    facilityId: "fac-001",
    pollutant: "Phosphorus",
    count: 2,
    exceedanceCount: 2,
    maxRatio: new Decimal("1.8"),
    severity: "MEDIUM",
    firstDate: new Date(Date.now() - 21 * 24 * 60 * 60 * 1000),
    lastDate: new Date(Date.now() - 14 * 24 * 60 * 60 * 1000),
    reportingYear: "2024",
    impairedWater: false,
    dismissed: false,
    notes: null,
    createdAt: new Date(Date.now() - 21 * 24 * 60 * 60 * 1000),
  },
  {
    id: "vio-003",
    facilityId: "fac-002",
    pollutant: "Total Suspended Solids",
    count: 1,
    exceedanceCount: 1,
    maxRatio: new Decimal("1.3"),
    severity: "LOW",
    firstDate: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000),
    lastDate: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000),
    reportingYear: "2024",
    impairedWater: false,
    dismissed: false,
    notes: null,
    createdAt: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000),
  },
  {
    id: "vio-004",
    facilityId: "fac-003",
    pollutant: "Total Nitrogen",
    count: 4,
    exceedanceCount: 4,
    maxRatio: new Decimal("3.2"),
    severity: "HIGH",
    firstDate: new Date(Date.now() - 10 * 24 * 60 * 60 * 1000),
    lastDate: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000),
    reportingYear: "2024",
    impairedWater: true,
    dismissed: false,
    notes: null,
    createdAt: new Date(Date.now() - 10 * 24 * 60 * 60 * 1000),
  },
]

export const mockStats = {
  totalFacilities: mockFacilities.length,
  totalSamples: mockViolations.reduce((sum, v) => sum + v.count, 0),
  totalViolations: mockViolations.length,
  activeAlerts: 3,
}
